image: node:latest
cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
        - client/node_modules/
        - server/node_modules/
    policy: pull
stages:
    - install
    - lint
    - build
#     - test
install:
    stage: install
    script:
        - pushd client
        - npm ci
        - popd
        - pushd server
        - npm ci
        - popd
    cache:
        key: "$CI_COMMIT_REF_NAME"
        paths:
            - client/node_modules/
            - server/node_modules/
        policy: pull-push
lint:client:
    stage: lint
    script:
        - pushd client
        - npm run lint
        - popd
# lint:server:
#     stage: lint
#     script:
#        - pushd server
#        - npm run lint
#        - popd
build:client:
    stage: build
    script:
        - pushd client
        - npm run build
        - popd
    artifacts:
        paths:
            - client/dist/
# build:server:
#     stage: build
#     script:
#         - pushd server
#         - npx tsc
#         - popd
#     artifacts:
#         paths:
#            - server/out/
# test:client:
#     only:
#         - master
#     stage: test
#     script:
#         - Xvfb :99 -ac -screen 0 1920x1080x24 &
#         - pushd client
#         - npm run coverage --browsers ChromeHeadlessNoSandbox
#         - popd
#     dependencies:
#         - build:client
#     artifacts:
#         paths:
#             - client/coverage/
# test:server:
#     only:
#         - master
#    stage: test
#    script:
#        - pushd server
#        - npm run coverage
#        - popd
#    dependencies:
#        - build:server
#    artifacts:
#        paths:
#            - server/coverage/
