image: xwiillz/node-yarn-firefox-chromium:latest
cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
        - client/node_modules/
        - server/node_modules/
    policy: pull
stages:
    - install
    - lint
    - build
#     - test
install:
    only:
        - master
    stage: install
    script:
        - pushd client
        - yarn
        - popd
        - pushd server
        - yarn
        - popd
    cache:
        key: "$CI_COMMIT_REF_NAME"
        paths:
            - client/node_modules/
            - server/node_modules/
        policy: pull-push
lint:client:
    only:
        - master
    stage: lint
    script:
        - pushd client
        - yarn lint
        - popd
lint:server:
    only:
       - master
    stage: lint
    script:
       - pushd server
       - yarn lint
       - popd
build:client:
    only:
        - master
    stage: build
    script:
        - pushd client
        - yarn build
        - popd
    artifacts:
        paths:
            - client/dist/
build:server:
    only:
        - master
    stage: build
    script:
        - pushd server
        - yarn tsc
        - popd
    artifacts:
        paths:
           - server/out/
# test:client:
#     only:
#         - master
#     stage: test
#     script:
#         - Xvfb :99 -ac -screen 0 1920x1080x24 &
#         - pushd client
#         - yarn coverage --browsers ChromeHeadlessNoSandbox
#         - popd
#     dependencies:
#         - build:client
#     artifacts:
#         paths:
#             - client/coverage/
# test:server:
#     only:
#         - master
#    stage: test
#    script:
#        - pushd server
#        - yarn coverage
#        - popd
#    dependencies:
#        - build:server
#    artifacts:
#        paths:
#            - server/coverage/
